language: node_js
node_js:
  - 12
install: npm install
script: npm test
deploy:
  provider: heroku
  api_key:
    secure: 59e9b9c7-db26-4036-9653-b2cd38df8e28
  app: web-ira-zozulya
  on:
    repo: irazozulya/web
  strategy: git